[package]
name = "server"
version = "0.1.0"
authors = ["Alexander Andreev <al101an@mail.ru>"]
edition = "2018"

[dependencies]
clap = "2"

protector = { path = "./protector" }
thread_pool = { path = "./thread_pool" }
