[package]
name = "server"
version = "0.1.0"
authors = ["Kirbina Valeriya <vkirbina@mail.ru>"]
edition = "2020"

[dependencies]
clap = "2"

protector = { path = "./protector" }
thread_pool = { path = "./thread_pool" }
